### ISSUE TITLE
Review z Reasu 🏠

### ISSUE THREAD

**Issue by tomaskallup** [DK8-PRG/reas-form#1]
Ahoj z Reasu!
Dan nás poprosil, abychom se ti podívali na vypracování testovacího úkolu, tak jsem se toho ujal.

Celkový dojem je hodně dobrý, funguje to suprově, validace tam je, mapka taky.

Narazil jsem spíš při rozběhání lokálně:
 - V readme je, že mám vytvořit `.env`, ale loaduje se `config.env`
 - `config.env` se loaduje na dvou místech (`server.js`, `utils/db.js`) - tohle je fakt drobnost a nemá to vliv na funkčnost
 - Frontend se napojí na produkční API (je natvrdo v kódu, chtělo by to přepínat, ideálně podle `NODE_ENV` nebo nějaké vlastní env proměnné), takže pro testování toho lokáního jsou potřeba úpravy (naštěstí si to v kódu nechal zakomentované, jen je tam špatný port)
 - Formulářem neprojdu, protože nemám kraje (tady by stačilo je `mongoexport`nout do JSONu a nechat v repu), ale v cloudu to běží, takže to není tak závažné.

Potom takové "nitpicky":
 - Kombinace češtiny & angličtiny v názvech proměnných a souborů - nemá vliv na funkčnost, jen je to zvláštní 😄 
 - V Readme je uveden "důraz na responzivitu", ale při přepnutí na mobilku se `/chci-nabidku` rozpadne

**Comment by DK8-PRG** [comment]
Ahoj,

díky moc za zpětnou vazbu! Co se týče problémů s lokálním spuštěním, soustředil jsem se hlavně na to, aby aplikace fungovala bez problémů v produkčním prostředí, a ne úplně jsem domyslel lokální spuštění 😅. Doupravím a odstraním ještě ty nedostatky. 

Ještě jednou díky za feedback!
